package dev.buijs.klutter.core.flutter


import dev.buijs.klutter.core.*
import dev.buijs.klutter.core.KlutterPrinter
import java.io.File
import kotlin.collections.HashMap

/**
 * @author Gillian Buijs
 * @contact https://buijs.dev
 */
internal class AndroidRootBuildGradleGenerator(
    private val root: Root,
    private val android: Android,
): KlutterFileGenerator() {

    override fun generate() = writer().write()

    override fun printer() = AndroidRootBuildGradlePrinter(properties())

    override fun writer() = AndroidRootBuildGradleWriter(android.file.resolve("build.gradle"), printer().print())

    private fun properties() = KlutterPropertiesReader(root.folder.resolve(".klutter/klutter.properties")).read()

}

internal class AndroidRootBuildGradlePrinter(
    private val props: HashMap<String, String>,
): KlutterPrinter {

    override fun print(): String {
        val kotlinVersion: String = get("kotlin.version")
        val gradleVersion: String = get("gradle.version")
        return """    
            |// Autogenerated by Klutter
            |// Do not edit directly
            |// Do not check into VCS
            |// See also: https://buijs.dev/klutter
            |buildscript {
            |    
            |    // Do not edit directly! Source of value is klutter.yaml.
            |    ext.kotlin_version = "$kotlinVersion"
            |    repositories {
            |        google()
            |        mavenCentral()
            |    }
            |    
            |    // Do not edit directly! Source of value is klutter.yaml.
            |    dependencies {
            |        classpath "com.android.tools.build:gradle:$gradleVersion"
            |        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
            |    }
            |}
            |
            |allprojects {
            |   def kProps = new Properties()
            |   new File(project.projectDir, ".klutter/klutter.properties")
            |           .getCanonicalFile()
            |           .withReader('UTF-8') { reader -> kProps.load(reader)}
            |
            |    repositories {
            |        google()
            |        mavenCentral()
            |        //todo upload artifacts to public repo and remove privates (ouch)
            |        maven {
            |            url = uri(kProps.getProperty('private.repo.url'))
            |            credentials {
            |                username = kProps.getProperty('private.repo.username')
            |                password = kProps.getProperty('private.repo.password')
            |            }
            |        }
            |    }
            |}
            |
            |rootProject.buildDir = '../build'
            |subprojects {
            |    project.buildDir = "${'$'}{rootProject.buildDir}/${'$'}{project.name}"
            |    project.evaluationDependsOn(':app')
            |}
            |
            |task clean(type: Delete) {
            |   delete rootProject.buildDir
            |}
    """.trimMargin()
    }

    private fun get(key: String) = props[key]
        ?: throw KlutterConfigException("klutter.properties is missing property: $key")

}

internal class AndroidRootBuildGradleWriter(val file: File, val content: String): KlutterWriter {

    override fun write(): KlutterLogger {
        val logger = KlutterLogger()

        if(file.exists()) {
            file.delete().also {
                logger.debug("Deleted build.gradle: $file")
            }
        } else logger.error("Build.gradle file in android folder not found. Creating a new file!")

        file.createNewFile().also { logger.debug("Created new build.gradle: $file") }
        file.writeText(content).also { logger.debug("Written content to $file:\r\n$content") }
        return logger
    }

}