package dev.buijs.klutter.core.flutter

import dev.buijs.klutter.core.*
import java.io.File

/**
 * @author Gillian Buijs
 * @contact https://buijs.dev
 */
internal class IosAppDelegateGenerator(
    private val methods: List<MethodCallDefinition>,
    private val ios: IOS,
    private val podName: String
) : KlutterFileGenerator() {

    override fun generate() = writer().write()

    override fun printer() = IosAppDelegatePrinter(methods, podName)

    override fun writer() = IosAppDelegateWriter(ios.appDelegate(), printer().print())

}

internal class IosAppDelegatePrinter(
    private val definitions: List<MethodCallDefinition>,
    private val podName: String,
): KlutterPrinter {

    override fun print() = """
        |//File generated by Klutter Framework.
        |//Do not edit directly!
        |
        |import UIKit
        |import Flutter
        |import $podName
        |
        |@UIApplicationMain
        |@objc class AppDelegate: FlutterAppDelegate {
        |  override func application(
        |    _ application: UIApplication,
        |    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
        |  ) -> Bool {
        |  
        |    GeneratedPluginRegistrant.register(with: self)
        |
        |    let channelName = "KLUTTER"
        |    let rootViewController = window?.rootViewController as! FlutterBinaryMessenger
        |    let methodChannel = FlutterMethodChannel(name: channelName, binaryMessenger: rootViewController)
        |
        |    methodChannel.setMethodCallHandler {(call: FlutterMethodCall, result: FlutterResult) -> Void in
        |    ${blocks()}
        |
        |    }
        |    
        |    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
        |    
        |  }
        |}
        """.trimMargin()

    private fun blocks() = if (definitions.isEmpty()) {
        "return result(FlutterMethodNotImplemented)"
    } else {
        val defs = definitions.joinToString("else") { printFun(it) }
        "$defs else { result(FlutterMethodNotImplemented) }"
    }

    private fun printFun(definition: MethodCallDefinition): String {
        return """
            | if (call.method == "${definition.getter}") {
            |        result(${definition.call})
            |      } """.trimMargin()
    }
}

internal class IosAppDelegateWriter(val file: File, val content: String): KlutterWriter {

    override fun write(): KlutterLogger {

        val logger = KlutterLogger()

        if(file.exists()){
            file.delete()
        }

        file.createNewFile().also {
            if(!file.exists()){
                throw KlutterCodeGenerationException("Unable to create file: $file.")
            } else logger.info("Created new AppDelegate.swift: $file")
        }

        file.writeText(content).also {
            logger.debug("Written content to AppDelegate.swfit: \r\n$content")
        }

        return logger
    }

}

