package dev.buijs.klutter.core.tasks.plugin

import dev.buijs.klutter.core.*
import dev.buijs.klutter.core.KlutterPrinter
import dev.buijs.klutter.core.KlutterWriter
import dev.buijs.klutter.core.tasks.shared.DefaultWriter
import java.io.File

/**
 * @author Gillian Buijs
 */
internal class FlutterPodspecGenerator(
    private val path: File,
    private val config: FlutterLibraryConfig,
    private val iosVersion: String,
): KlutterFileGenerator() {

    override fun printer() = FlutterPodspecPrinter(
        libraryName = config.libraryName,
        libraryDescription = config.libraryDescription,
        libraryVersion = config.libraryVersion,
        libraryHomepage = config.libraryHomepage,
        iosVersion = iosVersion,
    )

    override fun writer() = DefaultWriter(path, printer().print())

}

internal class FlutterPodspecPrinter(
    private val libraryName: String,
    private val libraryDescription: String,
    private val libraryVersion: String,
    private val libraryHomepage: String,
    private val iosVersion: String,
): KlutterPrinter {

    override fun print() = """
            |# Generated by Klutter framework.
            |# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html.
            |# Run `pod lib lint example_plugin.podspec` to validate before publishing.
            |#
            |Pod::Spec.new do |s|
            |  s.name             = '$libraryName'
            |  s.version          = '$libraryVersion'
            |  s.summary          = '$libraryDescription'
            |  s.description      = <<-DESC
            |A new Flutter project.
            |                       DESC
            |  s.homepage         = '$libraryHomepage'
            |  s.license          = { :file => '../LICENSE' }
            |  s.author           = { 'Your Company' => 'email@example.com' }
            |  s.source           = { :path => '.' }
            |  s.source_files = 'Classes/**/*'
            |  s.dependency 'Flutter'
            |  s.platform = :ios, '$iosVersion'
            |
            |  # Flutter.framework does not contain a i386 slice.
            |  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386' }
            |  s.swift_version = '5.0'
            |end
            |""".trimMargin()

}