package dev.buijs.klutter.core.tasks.plugin

import dev.buijs.klutter.core.*
import dev.buijs.klutter.core.KlutterPrinter
import dev.buijs.klutter.core.tasks.shared.DefaultWriter
import java.io.File

/**
 * @author Gillian Buijs
 */
internal class IosPluginHGenerator(
    private val path: File,
    private val pluginClassName: String,
): KlutterFileGenerator() {

    override fun printer() = IosPluginHPrinter(pluginClassName)

    override fun writer() = DefaultWriter(path, printer().print())

}

internal class IosPluginHPrinter(
    private val pluginClassName: String,
): KlutterPrinter {

    override fun print() = """
            |# Generated by Klutter framework.
            |#import <Flutter/Flutter.h>
            |
            |@interface $pluginClassName : NSObject<FlutterPlugin>
            |@end
            |
            |""".trimMargin()

}