/* Copyright (c) 2021 - 2022 Buijs Software
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */
package dev.buijs.klutter.core.tasks.plugin.flutter

import dev.buijs.klutter.core.*
import dev.buijs.klutter.core.KlutterPrinter
import dev.buijs.klutter.core.tasks.plugin.FlutterLibraryConfig
import dev.buijs.klutter.core.tasks.shared.DefaultWriter
import java.io.File

/**
 * @author Gillian Buijs
 */
internal class FlutterPodspecGenerator(
    private val path: File,
    private val config: FlutterLibraryConfig,
    private val iosVersion: String,
): KlutterFileGenerator() {

    override fun printer() = FlutterPodspecPrinter(
        libraryName = config.libraryName,
        libraryDescription = config.libraryDescription,
        libraryVersion = config.libraryVersion,
        libraryHomepage = config.libraryHomepage,
        iosVersion = iosVersion,
    )

    override fun writer() = DefaultWriter(path, printer().print())

}

internal class FlutterPodspecPrinter(
    private val libraryName: String,
    private val libraryDescription: String,
    private val libraryVersion: String,
    private val libraryHomepage: String,
    private val iosVersion: String,
): KlutterPrinter {

    override fun print() = """
            |# Generated by Klutter framework.
            |# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html.
            |# Run `pod lib lint example_plugin.podspec` to validate before publishing.
            |#
            |Pod::Spec.new do |s|
            |  s.name             = '$libraryName'
            |  s.version          = '$libraryVersion'
            |  s.summary          = '$libraryDescription'
            |  s.description      = <<-DESC
            |A new Flutter project.
            |                       DESC
            |  s.homepage         = '$libraryHomepage'
            |  s.license          = { :file => '../LICENSE' }
            |  s.author           = { 'Your Company' => 'email@example.com' }
            |  s.source           = { :path => '.' }
            |  s.source_files = 'Classes/**/*'
            |  s.dependency 'Flutter'
            |  s.platform = :ios, '$iosVersion'
            |
            |  # Flutter.framework does not contain a i386 slice.
            |  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386' }
            |  s.swift_version = '5.0'
            |end
            |""".trimMargin()

}