//File generated by Klutter Framework.
//Do not edit directly!

import UIKit
import Flutter
import common

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
  
    GeneratedPluginRegistrant.register(with: self)

    let channelName = "KLUTTER"
    let rootViewController = window?.rootViewController as! FlutterBinaryMessenger
    let methodChannel = FlutterMethodChannel(name: channelName, binaryMessenger: rootViewController)

    methodChannel.setMethodCallHandler {(call: FlutterMethodCall, result: FlutterResult) -> Void in
     if (call.method == "getGreeting") {
        result(Greeting().greeting())
      }  else { result(FlutterMethodNotImplemented) }

    }
    
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    
  }
}