/* Copyright (c) 2021 - 2022 Buijs Software
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

package dev.buijs.klutter.plugins.gradle.tasks.adapter.flutter


import dev.buijs.klutter.core.*
import dev.buijs.klutter.core.KlutterPrinter
import dev.buijs.klutter.plugins.gradle.dsl.KlutterRepository
import dev.buijs.klutter.plugins.gradle.tasks.adapter.dart.DartWriter
import org.gradle.api.logging.Logging
import java.io.File
import kotlin.collections.HashMap

/**
 * @author Gillian Buijs
 */
class AndroidRootBuildGradleGenerator(
    private val android: Android,
): KlutterFileGenerator() {

    override fun generate() = writer().write()

    override fun printer() = AndroidRootBuildGradlePrinter()

    override fun writer() = AndroidRootBuildGradleWriter(android.file.resolve("build.gradle"), printer().print())

}

/**
 * @author Gillian Buijs
 */
class AndroidRootBuildGradlePrinter: KlutterPrinter {

    override fun print(): String {
        val dollar = "$"
        return """    
            |// Autogenerated by Klutter
            |// Do not edit directly
            |// See: https://buijs.dev/klutter
            |buildscript {
            |
            |   def properties = new Properties()
            |   def propertiesFile = new File("$dollar{projectDir}/../buildSrc/buildsrc.properties")
            |   if (propertiesFile.exists()) {
            |       propertiesFile.withReader('UTF-8') { reader ->
            |           properties.load(reader)
            |       }
            |   } else {
            |       throw new GradleException("File not found ${dollar}propertiesFile")
            |   }
            |
            |   def kotlin = properties.getProperty('kotlin')
            |   if (kotlin == null) {
            |       throw new GradleException("Kotlin version not found. Define kotlin version in buildSrc/buildsrc.properties")
            |   }
            |
            |   def gradle = properties.getProperty('android.gradle')
            |   if (gradle == null) {
            |       throw new GradleException("Android Gradle tools version not found. Define android.gradle version in buildSrc/buildsrc.properties")
            |   }
            |
            |   def klutter = properties.getProperty('klutter')
            |   if (klutter == null) {
            |       throw new GradleException("Klutter version not found. Define klutter in buildSrc/buildsrc.properties")
            |   }
            |
            |   repositories {
            |       google()
            |       mavenCentral()
            |       maven { url = uri("https://repsy.io/mvn/buijs-dev/klutter") }
            |   }
            |
            |   dependencies {
            |       classpath "com.android.tools.build:gradle:${dollar}gradle"
            |       classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${dollar}kotlin"
            |       classpath "dev.buijs.klutter:core:${dollar}klutter"
            |   }
            |    
            |}
            |
            |allprojects {
            |    repositories {
            |        google()
            |        mavenCentral()
            |        maven { url = uri("https://repsy.io/mvn/buijs-dev/klutter") }
            |    }
            |}
            |
            |rootProject.buildDir = '../build'
            |subprojects {
            |    project.buildDir = "$dollar{rootProject.buildDir}/$dollar{project.name}"
            |}
            |
            |subprojects {
            |    project.evaluationDependsOn(':app')
            |}
            |
            |task clean(type: Delete) {
            |    delete rootProject.buildDir
            |}
    """.trimMargin()
    }

}


/**
 * @author Gillian Buijs
 */
class AndroidRootBuildGradleWriter(val file: File, val content: String): KlutterWriter {

    private val log = Logging.getLogger(AndroidRootBuildGradleWriter::class.java)

    override fun write() {

        if(file.exists()) {
            file.delete().also {
                log.debug("Deleted build.gradle: $file")
            }
        } else log.error("Build.gradle file in android folder not found. Creating a new file!")

        file.createNewFile().also { log.debug("Created new build.gradle: $file") }
        file.writeText(content).also { log.debug("Written content to $file:\r\n$content") }
    }

}