/* Copyright (c) 2021 - 2022 Buijs Software
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

package dev.buijs.klutter.plugins.gradle.tasks.adapter.flutter

import dev.buijs.klutter.core.*
import dev.buijs.klutter.core.KlutterPrinter
import java.io.File
import kotlin.collections.HashMap

/**
 * @author Gillian Buijs
 */
internal class AndroidBuildGradleGenerator(
    private val root: Root,
    private val android: File,
    private val kmpDependencies: List<String>,
): KlutterFileGenerator() {

    override fun generate() = writer().write()

    override fun printer() = AndroidBuildGradlePrinter(properties, aarFile(), android(), kmpDependencies)

    override fun writer() = AndroidBuildGradleWriter(android.resolve("build.gradle"), printer().print())

    private val properties = KlutterPropertiesReader(root.folder.resolve(".klutter/klutter.properties")).read()

    private fun aarFile() = root.folder.resolve(".klutter/kmp.aar")

    private fun android() = android

}

internal class AndroidBuildGradlePrinter(
    private val props: HashMap<String, String>,
    private val aarFileLocation: File,
    private val androidLocation: File,
    private val kmpDependencies: List<String>,
): KlutterPrinter {

    override fun print(): String {
        val appId: String = get("app.id").substringAfter("\"").substringBefore("\"")
        val appVersionName: String = get("app.version.name").substringAfter("\"").substringBefore("\"")
        val appVersionCode: Int = get("app.version.code").toInt()
        val compileSdk: Int = get("android.sdk.compile").toInt()
        val targetSdk: Int = get("android.sdk.target").toInt()
        val minSdk: Int = get("android.sdk.minimum").toInt()
        val kotlinVersion: String = get("kotlin.version").substringAfter("\"").substringBefore("\"")
        val kmpAnnotationsVersion: String = get("klutter.annotations.kmp.version").substringAfter("\"").substringBefore("\"")
        val flutterSdk: String = get("flutter.sdk.location").substringAfter("\"").substringBefore("\"")
        val kmpAarFile: String = aarFileLocation.relativeTo(androidLocation).toString()
        val kotlinxSerializationVersion: String = get("kotlinx.serialization.version")
        val kotlinxCoroutinesVersion: String = get("kotlinx.coroutines.version")

        val dependencies = mutableListOf(
            "implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion'",
            "implementation 'dev.buijs.klutter:annotations-kmp-android:$kmpAnnotationsVersion'",
            "implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:$kotlinxSerializationVersion'",
            "implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:$kotlinxCoroutinesVersion'",
            "runtimeOnly 'org.jetbrains.kotlinx:kotlinx-coroutines-android:$kotlinxCoroutinesVersion'",
            "implementation files('$kmpAarFile')"
        )

        kmpDependencies.forEach { dependency ->
            if(!dependencies.contains(dependency)){
                dependencies.add(dependency)
            }
        }

        return """
            |// Autogenerated by Klutter
            |// Do not edit directly
            |// Do not check into VCS
            |// See also: https://buijs.dev/klutter
            |
            |apply plugin: 'com.android.application'
            |apply plugin: 'kotlin-android'
            |apply from: "$flutterSdk/packages/flutter_tools/gradle/flutter.gradle"
            |
            |def keystoreProperties = new Properties()
            |def keystorePropertiesFile = rootProject.file('key.properties')
            |if (keystorePropertiesFile.exists()) {
            |    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
            |}
            |
            |if (!file("$kmpAarFile").exists()) {
            |    throw new GradleException("File '$kmpAarFile' does not exist. Please build kmp module first.")
            |}
            |
            |android {
            |    compileSdkVersion $compileSdk
            |
            |    compileOptions {
            |        sourceCompatibility JavaVersion.VERSION_1_8
            |        targetCompatibility JavaVersion.VERSION_1_8
            |    }
            |
            |    kotlinOptions {
            |        jvmTarget = '1.8'
            |    }
            |
            |    sourceSets {
            |        main.java.srcDirs += 'src/main/kotlin'
            |    }
            |
            |    defaultConfig {
            |        targetSdkVersion $targetSdk
            |        applicationId "$appId"
            |        minSdkVersion $minSdk
            |        versionCode $appVersionCode
            |        versionName "$appVersionName"
            |    }
            |
            |    signingConfigs {
            |        release {
            |            keyAlias keystoreProperties['keyAlias']
            |            keyPassword keystoreProperties['keyPassword']
            |            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            |            storePassword keystoreProperties['storePassword']
            |        }
            |    }
            |
            |    buildTypes {
            |        release {
            |            signingConfig signingConfigs.release
            |            shrinkResources false
            |            minifyEnabled false
            |        }
            |    }
            |}
            |
            |flutter {
            |    source '../..'
            |}
            |
            |dependencies {
            |${dependencies.sortedByDescending { it }.joinToString("\n") { "    $it" }}
            |}
            |
        """.trimMargin()
    }

    private fun get(key: String) = props[key]
        ?: throw KlutterConfigException("klutter.properties is missing property: $key")

}

class AndroidBuildGradleWriter(val file: File, val content: String): KlutterWriter {

    override fun write(): KlutterLogger {
        val logger = KlutterLogger()

        if(file.exists()) {
            file.delete().also {
                logger.debug("Deleted build.gradle: $file")
            }
        } else logger.error("Build.gradle file in android folder not found. Creating a new file!")

        file.createNewFile().also { logger.debug("Created new build.gradle: $file") }
        file.writeText(content).also { logger.debug("Written content to $file:\r\n$content") }
        return logger
    }

}