/* Copyright (c) 2021 - 2022 Buijs Software
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */
package dev.buijs.klutter.core.tasks.plugin.ios

import dev.buijs.klutter.core.*
import dev.buijs.klutter.core.KlutterPrinter
import dev.buijs.klutter.core.tasks.shared.DefaultWriter
import java.io.File

/**
 * @author Gillian Buijs
 */
internal class IosPluginMGenerator(
    private val path: File,
    private val pluginClassName: String,
    private val libraryName: String,
): KlutterFileGenerator() {

    override fun printer() = IosPluginMPrinter(pluginClassName, libraryName)

    override fun writer() = DefaultWriter(path, printer().print())

}

internal class IosPluginMPrinter(
    private val pluginClassName: String,
    private val libraryName: String,
): KlutterPrinter {

    override fun print() = """
            |# Generated by Klutter framework.
            |#import "$pluginClassName.h"
            |#if __has_include(<$libraryName/$libraryName-Swift.h>)
            |#import <$libraryName/$libraryName-Swift.h>
            |#else
            |// Support project import fallback if the generated compatibility header
            |// is not copied when this plugin is created as a library.
            |// https://forums.swift.org/t/swift-static-libraries-dont-copy-generated-objective-c-header/19816
            |#import "$libraryName-Swift.h"
            |#endif
            |
            |@implementation $pluginClassName
            |+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar>*)registrar {
            |  [Swift$pluginClassName registerWithRegistrar:registrar];
            |}
            |@end
            |""".trimMargin()

}