name: Publish Dokka to Github Pages

on:
  push:
env:
  KLUTTER_PRIVATE_USERNAME: ${{ secrets.KLUTTER_PRIVATE_USERNAME }}
  KLUTTER_PRIVATE_PASSWORD: ${{ secrets.KLUTTER_PRIVATE_PASSWORD }}
  KLUTTER_PRIVATE_URL: ${{ secrets.KLUTTER_PRIVATE_URL }}
  KLUTTER_JETBRAINS_CERTIFICATE_CHAINS: ${{ secrets.KLUTTER_JETBRAINS_CERTIFICATE_CHAINS }}
  KLUTTER_JETBRAINS_PRIVATE_KEY: ${{ secrets.KLUTTER_JETBRAINS_PRIVATE_KEY }}
  KLUTTER_JETBRAINS_PRIVATE_KEY_PASSWORD: ${{ secrets.KLUTTER_JETBRAINS_PRIVATE_KEY_PASSWORD }}

jobs:
  gradle:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - name: 'checkout source'
        uses: actions/checkout@v4
      - name: 'setup java'
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - name: 'setup gradle'
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.3
      - name: 'setup flutter'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - name: 'create docs'
        run: gradle dokkaHtmlMultiModule -p "lib"
      - name: 'upload to github pages'
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: lib/build/dokkaSite
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}