plugins {
    id("com.gradle.plugin-publish") version "0.16.0"
    id("java-gradle-plugin")
    id("klutter")
    id("klutter-java")
    id("klutter-test")
    id("maven-publish")
}

group = "dev.buijs.klutter"
version = dev.buijs.klutter.ProjectVersions.gradle

sourceSets {
    main {
        java {
            srcDirs("${projectDir.absolutePath}/src/main/kotlin")
        }
    }

    test {
        java {
            srcDirs("${projectDir.absolutePath}/src/test/kotlin")
        }
    }
}

sonarqube {
    isSkipProject = true
}

publishing {

    repositories {
        maven {
            url = dev.buijs.klutter.Repository.endpoint
            credentials {
                username =  dev.buijs.klutter.Repository.username
                password =  dev.buijs.klutter.Repository.password
            }
        }
    }

    publications {
        create<MavenPublication>("maven") {
            groupId = "dev.buijs.klutter"
            artifactId = "gradle-plugin"
            version = dev.buijs.klutter.ProjectVersions.gradle
            artifact("$projectDir/build/libs/plugin-gradle-${dev.buijs.klutter.ProjectVersions.gradle}.jar")

            pom {
                name.set("Klutter: Gradle Plugin")
                description.set("Gradle plugin for the Klutter Framework")
                url.set("https://buijs.dev/klutter/")

                licenses {
                    license {
                        name.set("MIT License")
                        url.set("https://github.com/buijs-dev/klutter/blob/main/LICENSE")
                    }
                }

                developers {
                    developer {
                        id.set("buijs-dev")
                        name.set("Gillian Buijs")
                        email.set("info@buijs.dev")
                    }
                }

                scm {
                    connection.set("git@github.com:buijs-dev/klutter.git")
                    developerConnection.set("git@github.com:buijs-dev/klutter.git")
                    url.set("https://github.com/buijs-dev/klutter")
                }
            }
        }
    }
}

pluginBundle {
    website = "https://buijs.dev/klutter/"
    vcsUrl = "https://github.com/buijs-dev/klutter"
    tags = listOf("klutter", "flutter", "kotlin", "multiplatform")
}

gradlePlugin {
    plugins {
        create("klutterGradlePlugin") {
            id = "dev.buijs.klutter.gradle"
            displayName = "Klutter plugin to generate boilerplate for connecting Flutter and Kotlin Multiplatform"
            description = "Klutter is a framework and tool set which uses Flutter to create the frontend and " +
                    "Kotlin Multiplatform for the backend. The connective layer is generated by the Klutter framework. " +
                    "This plugin contains all tasks needed to run a Klutter Project."
            implementationClass = "dev.buijs.klutter.plugins.gradle.KlutterGradlePlugin"
        }
    }
}

dependenciesTest {
    implementation.forEach {
        dependencies.add("testImplementation", it)
    }
}

dependenciesJava {
    implementation.forEach {
        dependencies.add("implementation", it)
    }
}

dependencies {
    implementation(project(":lib:core"))
    implementation(project(":lib:kompose"))
    implementation(project(":lib:annotations"))
    testImplementation(project(":lib:test"))
    testImplementation(gradleTestKit())
}